apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: shipwright-buildrun-start
spec:
  resourceRef:
    apiGroup: shipwright.io/v1alpha1
    kind: BuildRun
  selector:
    matchExpressions:
    - key: '.metadata.deletionTimestamp'
      operator: 'DoesNotExist'
    - key: '.status.phase'
      operator: 'In'
      values:
      - 'Pending'
  next:
    statusTemplate: |
      {{ $now := Now }}

      phase: Running
      startTimestamp: {{ $now | Quote }}
